# Generated by Django 3.0 on 2019-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='push_pull',
            field=models.CharField(blank=True, choices=[('push', 'upper body'), ('pull', 'lower body')], help_text='push or pull?', max_length=4, null=True),
        ),
    ]
