# Generated by Django 3.0 on 2019-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_exercise_push_pull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='part',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='push_pull',
        ),
        migrations.AddField(
            model_name='exercise',
            name='lower',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pull',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='push',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='upper',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
