# Generated by Django 3.0 on 2019-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20191206_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(choices=[('kb', 'Kettlebell'), ('db', 'Dumbbell'), ('bb', 'Barbell'), ('c2r', 'Rower'), ('aab', 'AAB'), ('c2s', 'Ski'), ('box', 'Box'), ('c2b', 'Airbike'), ('ghd', 'GHD'), ('sb', 'Sandbag'), ('jr', 'Jumprope'), ('rig', 'Rig'), ('rg', 'Rings')], help_text='Select equipment', max_length=3),
        ),
        migrations.AlterField(
            model_name='warmup',
            name='additional',
            field=models.TextField(blank=True, help_text='Add stuff to preexisting routine', max_length=1024),
        ),
    ]
