# Generated by Django 3.0 on 2019-12-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20191206_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warmup',
            name='save',
        ),
    ]
