# Generated by Django 3.0 on 2019-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20191206_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='Enter an exercise', max_length=64, verbose_name='Name'),
        ),
    ]
