# Generated by Django 3.0 on 2019-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20191209_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('g', 'Gymnastics'), ('w', 'Weightlifting'), ('m', 'Monostructural'), ('s', 'Strongman')], help_text='Gymnastics, Weightlifting ...', max_length=1, null=True),
        ),
    ]
