# Generated by Django 3.0 on 2019-12-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20191209_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='link',
            field=models.URLField(blank=True, db_index=True, max_length=256, unique=True),
        ),
    ]
