# Generated by Django 3.0 on 2019-12-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_exercise_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='link',
            field=models.URLField(blank=True, db_index=True),
        ),
    ]
