# Generated by Django 3.0 on 2019-12-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20191209_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='link',
        ),
    ]
