# Generated by Django 3.0 on 2019-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_remove_exercise_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
