# Generated by Django 3.0 on 2019-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_exercise_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='link',
            field=models.URLField(blank=True, help_text='Enter link to explanatory video to display it if needed somewhere'),
        ),
        migrations.AlterField(
            model_name='trainingpart',
            name='benchmark',
            field=models.BooleanField(blank=True, default=False, help_text='Will be stored for reuse'),
        ),
    ]
