# Generated by Django 2.2.8 on 2019-12-10 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20191209_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warmup',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
