# Generated by Django 2.2.8 on 2019-12-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_auto_20191210_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Jonas', max_length=124),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Neukamm', max_length=124),
            preserve_default=False,
        ),
    ]
