# Generated by Django 2.2.8 on 2019-12-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_auto_20191210_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='warmup',
        ),
        migrations.AddField(
            model_name='workout',
            name='warmup',
            field=models.ManyToManyField(blank=True, help_text='Enter warmup, if necessary', to='planner.Warmup'),
        ),
    ]
